### ISSUE TITLE
Feature Request: Eye Dropper Color Picker

### ISSUE THREAD

**Issue by zerismo** [brianpkelley/md-color-picker#114]
Do you have plans to implement an eye dropper with the color picker?
Would love to contribute on that, if that's something you are looking at.

**Comment by brianpkelley** [comment]
I've been under the impression this was impossible.  Due to [security violations](https://stackoverflow.com/questions/1936021/javascript-eyedropper-tell-color-of-pixel-under-mouse-cursor) in the browsers.  

Going forward the color picker will support custom tabs ([example](https://github.com/brianpkelley/md-color-picker/blob/feature/Plugin-Rewrite/src/js/mdColorPickerConfig.js#L148-L247), [a bit more in depth](https://github.com/brianpkelley/md-color-picker/blob/feature/Plugin-Rewrite/src/js/tabs/genericPalette.js)). And I'll either be opening up the tabs to pull requests or linking to other users repos.  Either way, I'll gladly accept any help possible.
